// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8zj6UJ6lUixNsiOMYF7buy79_gd_3pTI',
    appId: '1:751210563328:web:bc03442b9dca64917395e5',
    messagingSenderId: '751210563328',
    projectId: 'hovee-attendance',
    authDomain: 'hovee-attendance.firebaseapp.com',
    storageBucket: 'hovee-attendance.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf_PiBWr8U_fpfODRHQYog5v3GA9M5YY0',
    appId: '1:751210563328:android:35fed7a237a4cb9a7395e5',
    messagingSenderId: '751210563328',
    projectId: 'hovee-attendance',
    storageBucket: 'hovee-attendance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEliFYKSjs5R8l9hjHHZYUE8adsox9b0A',
    appId: '1:751210563328:ios:cd6ea971bef589a27395e5',
    messagingSenderId: '751210563328',
    projectId: 'hovee-attendance',
    storageBucket: 'hovee-attendance.firebasestorage.app',
    iosBundleId: 'com.hoveeAtt.organization',
  );
}
